# Generated by Django 5.2 on 2025-04-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_completed_tests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='rank',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avarage_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
