# Generated by Django 5.2 on 2025-04-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_rank_customuser_avarage_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='avarage_score',
            new_name='average_score',
        ),
    ]
