# Generated by Django 5.2 on 2025-04-29 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_otp_phone_otp_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='is_expire',
            new_name='is_expired',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='key',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='tried',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='username',
        ),
        migrations.AddField(
            model_name='otp',
            name='code',
            field=models.CharField(default='0000', max_length=6),
        ),
        migrations.AddField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
