from django.urls import path
from .views import (
    IndexView,
    TestsView,
    ResultView,
    PageNotFoundView,
    AboutView,
    ReadyToTestView,
    TestView,
    GetStartedTestsView,
    ExploreTestsView,
    CategoryView,
    NewCategoryView,
    NewTestView,
    NewQuestionView,
    UpdateCategoryView,
    UpdateTestView,
    UpdateQuestionView,
    DeleteCategoryView,
    DeleteTestView,
    DeleteQuestionView,
    ManageCategoriesView,
    ManageTestsView,
    ManageQuestionsView,
    toggle_saved_test,
)

app_name = 'main'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<int:test_id>/test', TestView.as_view(), name='test'),
    path('tests', TestsView.as_view(), name='tests'),
    path('<int:checktest_id>/result', ResultView.as_view(), name='result'),
    path('error/404', PageNotFoundView.as_view(), name='error_404'),
    path('about', AboutView.as_view(), name='about'),
    path('<int:test_id>/ready_to_test', ReadyToTestView.as_view(), name='ready_to_test'),
    path('get-started', GetStartedTestsView.as_view(), name='get_started'),
    path('explore', ExploreTestsView.as_view(), name='explore'),
    path('category/<str:category_name>', CategoryView.as_view(), name='category'),
    path('new-category', NewCategoryView.as_view(), name='new_category'),
    path('new-test', NewTestView.as_view(), name='new_test'),
    path('new-question', NewQuestionView.as_view(), name='new_question'),
    path('<int:category_id>/update-category', UpdateCategoryView.as_view(), name='update_category'),
    path('<int:test_id>/update-test', UpdateTestView.as_view(), name='update_test'),
    path('<int:question_id>/update-question', UpdateQuestionView.as_view(), name='update_question'),
    path('<int:category_id>/delete-category', DeleteCategoryView.as_view(), name='delete_category'),
    path('<int:test_id>/delete-test', DeleteTestView.as_view(), name='delete_test'),
    path('<int:question_id>/delete-question', DeleteQuestionView.as_view(), name='delete_question'),
    path('manage-categories', ManageCategoriesView.as_view(), name='manage_categories'),
    path('manage-tests', ManageTestsView.as_view(), name='manage_tests'),
    path('manage-questions', ManageQuestionsView.as_view(), name='manage_questions'),
    path('toggle-saved/', toggle_saved_test, name='toggle_saved_test'),
]