# Generated by Django 5.2 on 2025-04-18 11:39

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('a', models.CharField(max_length=300)),
                ('b', models.CharField(max_length=300)),
                ('c', models.CharField(max_length=300)),
                ('d', models.CharField(max_length=300)),
                ('correct_answer', models.CharField(help_text='E.x: a', max_length=300)),
            ],
            options={
                'verbose_name': 'questoin',
                'verbose_name_plural': 'questoins',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('max_attempt', models.PositiveSmallIntegerField()),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=datetime.datetime(2025, 4, 28, 11, 39, 6, 605420, tzinfo=datetime.timezone.utc))),
                ('pass_percentage', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'test',
                'verbose_name_plural': 'tests',
            },
        ),
    ]
