# Generated by Django 5.2 on 2025-04-18 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 15, 10, 23, 220761, tzinfo=datetime.timezone.utc)),
        ),
    ]
