# Generated by Django 5.2 on 2025-04-20 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_question_options_question_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='icon_class',
            field=models.CharField(default='fa fa-folder', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 30, 10, 42, 52, 314509, tzinfo=datetime.timezone.utc)),
        ),
    ]
