# Generated by Django 5.2 on 2025-04-20 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_test_icon_class_alter_test_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='completed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 30, 10, 48, 45, 879932, tzinfo=datetime.timezone.utc)),
        ),
    ]
