# Generated by Django 5.2 on 2025-04-20 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_test_completed_count_alter_test_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rtacha"), ('hard', 'Qiyin')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='test',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rtacha"), ('hard', 'Qiyin')], default='easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 30, 11, 55, 14, 446121, tzinfo=datetime.timezone.utc)),
        ),
    ]
