# Generated by Django 5.2 on 2025-04-20 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_question_code_alter_question_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(default='html', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 30, 13, 17, 10, 894493, tzinfo=datetime.timezone.utc)),
        ),
    ]
