# Generated by Django 5.2 on 2025-04-28 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_question_difficulty_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 9, 40, 6, 575749, tzinfo=datetime.timezone.utc)),
        ),
    ]
