# Generated by Django 5.2 on 2025-04-28 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_test_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 9, 42, 0, 383226, tzinfo=datetime.timezone.utc)),
        ),
    ]
