# Generated by Django 5.2 on 2025-04-29 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_test_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='checktest',
            name='spent_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=1200)),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 9, 7, 7, 46, 505431, tzinfo=datetime.timezone.utc)),
        ),
    ]
