# Generated by Django 5.2 on 2025-04-29 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_test_end_time_comment_savedtest_reactiontest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 9, 11, 20, 54, 64644, tzinfo=datetime.timezone.utc)),
        ),
    ]
