# Generated by Django 5.2 on 2025-04-29 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_test_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 9, 13, 37, 50, 947610, tzinfo=datetime.timezone.utc)),
        ),
    ]
