# Generated by Django 5.2 on 2025-05-06 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_test_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedtest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 5, 54, 0, 214336, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 5, 54, 0, 210418, tzinfo=datetime.timezone.utc)),
        ),
    ]
